#!/bin/sh -e
#
# cert-update.sh

[ -w /etc/ssl ] || {
	echo "${0##*/}: required root to update cert."
	exit 1
}

curl -s -o /etc/ssl/cert.pem http://curl.haxx.se/ca/cacert.pem
echo "${0##*/}: cert.pem updated."
